title: Ahnix
email: ramon@ahnix.com.br
description: >- # this means to ignore newlines until "baseurl:"
  Engenharia de Software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "ahnix.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter: RamonAlmeida_
github:  Ahnix
permalink: /:title/

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
